title: My Docs
description: Tài liệu hệ thống

theme: just-the-docs

# Tự động áp dụng layout mặc định cho tất cả trang
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

# Cấu hình Just the Docs
just_the_docs:
  nav_sort: case_sensitive
