title: My Docs
description: Tài liệu hệ thống

remote_theme: just-the-docs

# Tự động áp dụng layout mặc định cho tất cả trang
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

# Cấu hình Just the Docs
just_the_docs:
  nav_sort: case_sensitive
  collections:
    enabled: true # Kích hoạt navigation từ collections
  search:
    enabled: true # Kích hoạt tìm kiếm

# Định nghĩa collections cho các folder/file
collections:
  docs:
    output: true # Cho phép hiển thị nội dung trong nav
    permalink: /:collection/:path/
