title: My Docs
description: Tài liệu hệ thống

remote_theme: just-the-docs/just-the-docs

url: https://lelongc.github.io/aws

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      nav_exclude: false

just_the_docs:
  nav_sort: case_sensitive
  nav_fold: true