title: My Docs
description: Tài liệu hệ thống

remote_theme: just-the-docs

# Tự động áp dụng layout mặc định cho tất cả markdown
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      nav_exclude: false

# Kích hoạt cấu trúc điều hướng tự động
just_the_docs:
  nav_sort: case_sensitive
  collections: # tắt collections
    enabled: false
  search:
    enabled: true