---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: app-name
data:
  # Configuration values as key-value pairs
  app.properties: |
    log.level=INFO
    server.port=8080
    feature.flag.new-feature=true
    cache.ttl=3600
  db_host: "db.example.internal"
  db_port: "5432"
  db_name: "appdb"
  # JSON configuration
  config.json: |
    {
      "apiEndpoints": {
        "users": "/api/users",
        "products": "/api/products"
      },
      "features": {
        "darkMode": true,
        "betaFeatures": false
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app: app-name
type: Opaque
data:
  # Values must be base64 encoded
  # Example: echo -n "your-secret-value" | base64
  db_username: YWRtaW4= # admin
  db_password: cGFzc3dvcmQxMjM= # password123
  api_key: aHR0cHM6Ly9rdWJlcm5ldGVzLmlv # https://kubernetes.io
  oauth:
    clientId: Y2xpZW50LWlk
    clientSecret: Y2xpZW50LXNlY3JldA==
stringData:
  # Values provided as clear text (will be encoded by Kubernetes)
  # Good for values that change often or are provided by CI/CD
  LICENSE_KEY: "ABCD-EFGH-IJKL-MNOP"
  SMTP_PASSWORD: "not-so-secret-smtp-password"
