version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.5.5/terraform_1.5.5_linux_amd64.zip
      - unzip terraform_1.5.5_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo "Validating Terraform code..."
      - cd $CODEBUILD_SRC_DIR/regions/$REGION
      - terraform init -backend=false
      - terraform validate
      - terraform fmt -check -recursive

  build:
    commands:
      - echo "Planning Terraform changes..."
      - cd $CODEBUILD_SRC_DIR/regions/$REGION
      - terraform init -backend-config="../../config/$ENV/$REGION-backend.hcl"
      - terraform plan -var-file="../../config/$ENV/$REGION.tfvars" -out=tfplan
      
      # Only apply in non-prod environments unless explicitly approved
      - |
        if [ "$ENV" != "prod" ] || [ "$APPROVED" = "true" ]; then
          echo "Applying Terraform changes..."
          terraform apply tfplan
        else
          echo "Skipping apply for production without approval"
        fi

artifacts:
  files:
    - regions/$REGION/tfplan
    - regions/$REGION/terraform.tfstate
  discard-paths: no

cache:
  paths:
    - '/root/.terraform.d/**/*'
