# Thông tin cơ bản
site_name: DraDoc
repo_url: https://github.com/lelongc/aws
site_url: https://lelongc.github.io/aws/
edit_uri: edit/main/my-website/docs/
copyright: "Copyright © Lê Long C. 2025"

# Theme Material for MkDocs
theme:
  name: material
  language: vi
  custom_dir: overrides
  icon:
    logo: material/aws
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Chuyển sang chế độ tối
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Chuyển sang chế độ sáng
  features:
    # - navigation.instant
    # - navigation.instant.progress
    - navigation.top
    - navigation.sections
    - navigation.search
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.paths
    - navigation.indexes
    - navigation.indexes.sticky
    - navigation.prune
    - content.code.copy
    - content.action.edit
    - content.images.lazy
    # - toc.integrate
    - toc.follow
    - toc.expand
    # - header.autohide

# Plugins
plugins:
  - search
  - glightbox
  - git-revision-date-localized
  # Nếu muốn bật meta descriptions thì thêm vào requirements.txt:
  # - meta:
  #     meta_file: meta.yml

# Markdown Extensions
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.extra

# Extra config
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lelongc
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/long-lê-190l/
