# Thông tin cơ bản
site_name: DraDoc
repo_url: https://github.com/lelongc/aws # Link đến repo của bạn
site_url: https://lelongc.github.io/aws/ # Thêm URL khi bạn triển khai
edit_uri: edit/main/my-website/docs/ # <<< BỎ COMMENT VÀ ĐÃ CẤU HÌNH

# Theme Material for MkDocs
theme:
  name: material
  language: vi

  palette:
    # ... (giữ nguyên cấu hình palette) ...
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Chuyển sang chế độ tối
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Chuyển sang chế độ sáng

  features:
    # Navigation Features
    - navigation.top
    - navigation.sections
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.instant
    - navigation.instant.preview
    - navigation.indexes
    - navigation.indexes.sticky
    - navigation.search
    - navigation.search.highlight
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.paths
    - navigation.tracking

    # Search Features
    - search.suggest
    - search.highlight
    - search.share

    # Content Features
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.action.view
    - content.action.edit
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - content.images.lazy
    - content.images.zoom
    - content.math

    # Table of Contents Features
    - toc.integrate
    - toc.follow
    - toc.expand
        # ... (giữ nguyên plugins và markdown_extensions) ...
plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - toc:
      permalink: true
  - attr_list