# Thông tin cơ bản
site_name: DraDoc
repo_url: https://github.com/lelongc/aws # Link đến repo của bạn
site_url: https://lelongc.github.io/aws/ # Thêm URL khi bạn triển khai
edit_uri: edit/main/my-website/docs/ # <<< BỎ COMMENT VÀ ĐÃ CẤU HÌNH

# Theme Material for MkDocs
theme:
  name: material
  language: vi

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Chuyển sang chế độ tối
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Chuyển sang chế độ sáng

  features:
  - navigation.top
  - navigation.sections
  - navigation.search
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.footer
  - navigation.paths
  - navigation.indexes
  - navigation.indexes.sticky

  - content.code.copy
  - content.action.edit
  - content.images.lazy

  - toc.integrate
  - toc.follow
  - toc.expand

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true