name: Build and Deploy with Auto Front Matter

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Auto-add front matter to Markdown files
        shell: bash
        run: |
          echo "Processing Markdown files..."
          # Duyệt tất cả file .md (ngoại trừ trong _site và .github)
          find . -type f -name "*.md" ! -path "./_site/*" ! -path "./.github/*" | while read file; do
            # Nếu dòng đầu tiên không bắt đầu bằng ---
            if ! head -n 1 "$file" | grep -q "^---"; then
              echo "Adding front matter to $file"
              # Lấy tên file không có phần mở rộng
              filename=$(basename "$file" .md)
              tmp=$(mktemp)
              {
                echo "---"
                echo "title: \"$filename\""
                echo "---"
                echo
                cat "$file"
              } > "$tmp"
              mv "$tmp" "$file"
            fi
          done

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4