name: Build and Deploy Just the Docs

on:
  push:
    branches: ["main"]
    paths:
      - "./**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Create Gemfile (if not exists)
        run: |
          if [ ! -f Gemfile ]; then
            echo "source 'https://rubygems.org'" > Gemfile
            echo 'gem "github-pages", group: :jekyll_plugins' >> Gemfile
            echo 'gem "just-the-docs"' >> Gemfile
          fi

      - name: Install dependencies
        run: bundle install

      - name: Auto-add front matter to Markdown files
        run: |
          echo "Processing Markdown files..."
          find . -type f -name "*.md" ! -path "./_site/*" ! -path "./.github/*" | while read file; do
            if ! head -n 1 "$file" | grep -q "^---"; then
              filename=$(basename "$file" .md)
              # Thay đổi dấu '-' thành khoảng trắng và viết hoa chữ cái đầu
              title=$(echo "$filename" | sed 's/-/ /g' | sed 's/.*/\u&/')
              echo "Adding front matter to $file with title: $title"
              tmp=$(mktemp)
              {
                echo "---"
                echo "title: \"$title\""
                echo "---"
                echo
                cat "$file"
              } > "$tmp"
              mv "$tmp" "$file"
            fi
          done

      - name: Build site with Jekyll
        run: bundle exec jekyll build

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4