name: Build and Deploy Just the Docs

on:
  push:
    branches: [main]
    paths:
      - "./**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add default front matter to .md files
        run: |
          find docs -name "*.md" | while read file; do
            if ! grep -q '^---' "$file"; then
              filename=$(basename "$file" .md)
              title=$(echo "$filename" | sed 's/-/ /g' | sed 's/.*/\u&/')
              echo -e "---\ntitle: $title\n---\n$(cat "$file")" > "$file"
            fi
          done

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Install dependencies
        run: |
          cd docs
          echo -e "source 'https://rubygems.org'\ngem 'github-pages', group: :jekyll_plugins" > Gemfile
          echo "gem 'just-the-docs'" >> Gemfile
          bundle install

      - name: Build site
        run: |
          cd docs
          bundle exec jekyll build

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4