name: MkDocs Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd my-website # Thêm dòng này để di chuyển vào thư mục my-website
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Nếu bạn có file requirements.txt
          pip install mkdocs mkdocs-material # Thay thế bằng theme và các plugin bạn đang dùng

      - name: Build the MkDocs site
        run: |
          cd my-website # Thêm dòng này để di chuyển vào thư mục my-website
          mkdocs build --verbose

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./my-website/site # Điều chỉnh đường dẫn đến thư mục site
